{% set version = "4.3.0" %}

package:
  name: netcdf-cxx4
  version: {{ version }}

source:
  fn: netcdf-cxx4-{{ version }}.tar.gz
  url: https://github.com/Unidata/netcdf-cxx4/archive/v{{ version }}.tar.gz
  sha256: 25da1c97d7a01bc4cee34121c32909872edd38404589c0427fefa1301743f18f

build:
  number: 3
  skip: True  # [win]

requirements:
  build:
    - cmake
    - libnetcdf 4.4.*
    - toolchain
  run:
    - libnetcdf 4.4.*

test:
  commands:
    #- ncxx4-config --all  # FIXME: no ncxx4-config for cmake yet.
    - test -f ${PREFIX}/lib/libnetcdf-cxx4.a  # [unix]
    - test -f ${PREFIX}/lib/libnetcdf_c++4.a  # [unix]
    - conda inspect linkages -p $PREFIX netcdf-cxx4  # [not win]
    - conda inspect objects -p $PREFIX netcdf-cxx4  # [osx]

about:
  home: https://github.com/Unidata/netcdf-cxx4
  license: http://www.unidata.ucar.edu/software/netcdf/copyright.html
  summary: Unidata NetCDF C++ Library

extra:
  recipe-maintainers:
    - kmuehlbauer
    - ocefpaf
