# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "d8l8SnnLwV77UVfbvXbXffhJyzRgcY3mNw+NKu9nNJE5drUIea9WyM52pmjI5+BTvWtgQTsRkIsYVJKTF7IXRlRR4O91hlBfAXsRZJQ6VEgIkHi2m2hIoGs+DH7TKHG1jMs3tdj0ReKedvhb2f4y/zaw+ca5NXxPm0AEsp8qOxty8lftEzjONNhhs6EG0P1yj5g+zuawl/rOPExhT8qTslCgaCctxJUOzxNp4ORnn+/Tt53g8bIJJyQ8Dfar+QUoSpKVc0DPhL6Suvy6HfIxDa9ikX1H1UVZDX5feGn7GPT2SRE0kh9a8FDHIIoDVUq9AsniALlSOv67X+TAsX5x1azDWublm7RvCAT3Fj6pp+ojZQB/jZn8FG3ckdyVJIkzel6ULFIFMj8u/KrWXU74SPTBJoV1rwXe/CpjRChUbgGPtUiskJGPj+TbG3Xd9adF7cs8wFwFKQZJgAE4B0G2eWgfOlTC9GtIVg12n9ipUbuIvU05YzQsNwbXs/LhuByueqZwsPuFAkrKWZXw62+/KOG7PX/UTDfI7c2QZCyFDvfutZElO1HBhHZYQxnAnM3YWvPXFtDnlnQ+S6mjnIDOf+jQYPdZoXOvexgpv4IaLFm8Gt+73+vrEa8g5es1/6LqgMFZOYiRGXM0/NPPHbFRlUfebkegvToly/kOXiVOmMc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
