travis:
  secure:
    BINSTAR_TOKEN: OLr7geGU8qJD2O3cI0XRnw3Zq/8EwbkhkFK6MrBY1lycRNgH5sOW4acdpZmJ14+z5v4O4G7WUenqJFiPw7v09uJO5z2xy/amMg9YMpIzxdDHrATdfkPlgMLXuqMRX1+ALll/xAq6ph0nf4GS1COZIdeTa2hjWoK9iKilZy6Rqs0qSzH1ciVP2Xlkq0wE8FYEPevWCTFFxwbaXHDhFIsLUvemsYHQm510EoScPghgsjM8lX1qleQln74wl1aNOSImrEV/ej7oGomosWDjFA4bp2glEu0WGeeSQ5jOLtrsj1WMpcBpyBYYqi7hC7u0IdJj+i0Gl7vyVhJRgZ4u/UOAzn1BtZKraV9T+kiExQcHsSNegaKcilJvxvmIbYLIny+y7A+XsDH0GZYkm/0+5IYSaV4X6U++u3IyarvCjszmjPALkb3KmOxDr1HSETV61U9AcD9sNkkK2txlUe4hez+nJU2KyMCDp3LCfNC2dWTXkpT0Bl0w9NpwPGWyCjf1UQJpuMyGc+MW8dQRApIzQroboCWgEspXlRtAGTIwSTlQKeij8yP3yG8PKjz1GSZjeYGn5klsxz83gZQCh0Ryh8VIsJa4K/LkU+8K0temNULIjeQ7riNDkhPb4wa2ig9ru0qDI24xV9jjMReKDbvNgTQr3H/gF7R94tteWSh22pbM7fA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
