travis:
  secure:
    BINSTAR_TOKEN: d8l8SnnLwV77UVfbvXbXffhJyzRgcY3mNw+NKu9nNJE5drUIea9WyM52pmjI5+BTvWtgQTsRkIsYVJKTF7IXRlRR4O91hlBfAXsRZJQ6VEgIkHi2m2hIoGs+DH7TKHG1jMs3tdj0ReKedvhb2f4y/zaw+ca5NXxPm0AEsp8qOxty8lftEzjONNhhs6EG0P1yj5g+zuawl/rOPExhT8qTslCgaCctxJUOzxNp4ORnn+/Tt53g8bIJJyQ8Dfar+QUoSpKVc0DPhL6Suvy6HfIxDa9ikX1H1UVZDX5feGn7GPT2SRE0kh9a8FDHIIoDVUq9AsniALlSOv67X+TAsX5x1azDWublm7RvCAT3Fj6pp+ojZQB/jZn8FG3ckdyVJIkzel6ULFIFMj8u/KrWXU74SPTBJoV1rwXe/CpjRChUbgGPtUiskJGPj+TbG3Xd9adF7cs8wFwFKQZJgAE4B0G2eWgfOlTC9GtIVg12n9ipUbuIvU05YzQsNwbXs/LhuByueqZwsPuFAkrKWZXw62+/KOG7PX/UTDfI7c2QZCyFDvfutZElO1HBhHZYQxnAnM3YWvPXFtDnlnQ+S6mjnIDOf+jQYPdZoXOvexgpv4IaLFm8Gt+73+vrEa8g5es1/6LqgMFZOYiRGXM0/NPPHbFRlUfebkegvToly/kOXiVOmMc=
appveyor:
  secure:
    BINSTAR_TOKEN: !!binary |
      TVA0aFpZeWxEeVVXRXNydDN1M2NvZDJzYkZlUndVemlIMDJtdlFPZGJqc1RPL2wxeUl4RGtQLzc2
      clNJamNHQw==
